server:
  port: 8080
spring:
  #  debug: false
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      temp:
      user_jdbc_metdata_defaults: false
      use_jdbc_metadata_defaults: false

